spring:
  aop:
    proxy-target-class: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  application:
    name: gateway

security:
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://59.110.161.121:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret

    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----

zuul:
  routes:
    resource:
      path: /resource/**
      serviceId: example-resource
      stripPrefix: false
#      url: http://localhost:9000
#    user:
#      path: /user/**
#      url: http://localhost:9999/uaa/user
    idgenerator: 
      path: /idgenerator/**
      service-id: idgenerator
    levelserver: 
      path: /battle/**
      service-id: levelserver
    itemserver: 
      path: /bags/**
      service-id: itemserver 
    logserver: 
      path: /log/** 
      service-id: logserver
    usersetting: 
      path: /settings/**
      service-id: usersettingserver
    destroyerserver: 
      path: /destroyer/**
      service-id: destroyerserver

logging:
  level:
    org.springframework.security: DEBUG